version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_db:/var/lib/mysql
    networks:
      - inception-network
    expose:
      - "3306"

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_db:/var/www/wordpress
    networks:
      - inception-network
    expose:
      - "9000"

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: on-failure
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress_db:/var/www/wordpress
    networks:
      - inception-network

volumes:
  wordpress_db:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rarahhal/data/wordpress'
  mariadb_db:
    driver: 'local'
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/rarahhal/data/mariadb'

networks:
  inception-network:
    driver: bridge

